#Automatically generated by Colaboratory.

# file is located at
#    https://colab.research.google.com/drive/1WHpFZvnb2_aNYqEp2arXC5PjyFE1g8Vz

"""

import pandas as pd

data = pd.read_csv('sample_data/california_housing_train.csv')

filtered_data = data[(data['population'] >= 0) & (data['population'] <= 500)]

average_house_price = filtered_data['median_house_value'].mean()


"""

# Задача2

import pandas as pd

data = pd.read_csv('sample_data/california_hous_train.csv')

min_popul = data['population'].min()

filter_data = data[data['population'] == min_popul]

max_hholds = filter_data['households'].max()

print(f"Максимальное значение households в зоне минимального значения population: {max_hholds}")



 ## HW ending
